todo/urls.py
from django.urls import path
from . import views

app_name = "todo"
urlpatterns =[
    path('', views.ToDoListView.as_view(), name="todo_list"),
    path('create', views.CreateTaskView.as_view(), name="create_task")
]

todosite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls')),
]

todo/models.py
from django.db import models
from django.urls import reverse


class Task(models.Model):
    """" Model representing a toDo item"""
    title = models.CharField(max_length=200)
    description = models.TextField()
    startDate = models.DateTimeField()
    limitDate = models.DateTimeField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('todo:todo_list')

todo/forms.py
from django import forms
from todo.models import Task


class AddTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'startDate', 'limitDate']
        widgets = {
            'title' : forms.TextInput(attrs={'class': 'form-control'}),
            'description' : forms.Textarea(attrs={'class': 'form-control'}),
            'startDate' : forms.DateTimeInput(attrs={'class': 'form-control', 'type': 'datetime-local'}),
            'limitDate' : forms.DateTimeInput(attrs={'class': 'form-control', 'type': 'datetime-local'})
        }
        labels = {
            'title': 'Title',
            'description': 'Description',
            'startDate': 'Start Date',
            'limitDate': 'End Date'
        }

todo/views.py
from django.views import generic

from todo.forms import AddTaskForm
from todo.models import Task


class ToDoListView(generic.ListView):
    template_name = "todo/list.html"
    context_object_name = "todo_items"

    def get_queryset(self):
        return Task.objects.all()

class CreateTaskView(generic.CreateView):
    model = Task
    form_class = AddTaskForm
    template_name = "todo/create.html"

todo/templates/todo/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>MyToDo</title>
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
            <script type = "text/javascript" src="{% static 'todo/js/delete_modal.js' %}" ></script>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'todo:todo_list' %}">MyToDo</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
              <div class="navbar-nav">
                <a class="nav-link active" aria-current="page" href="{% url 'todo:todo_list' %}">Home</a>
                <a class="nav-link" href="#">History</a>
              </div>
              <div class="navbar-nav ms-auto">
                  <a class="nav-link" href="{% url 'todo:create_task' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-square-fill" viewBox="0 0 16 16">
                      <path d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2zm6.5 4.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3a.5.5 0 0 1 1 0"/>
                    </svg>
                </a>
              </div>
            </div>
          </div>
        </nav>
        {% block content %}
        {% endblock %}

    </body>
</html>

todo/templates/todo/create.html
{% extends 'todo/base.html' %}
{% block content %}
    <div class="py-5">
        <div class="container">
            <h3>Add Task</h3>
            <div class="form-group">
                <form method="POST" enctype="multipart/form-data">

                    <!-- Security token -->
                    {% csrf_token %}

                    <!-- Using the formset -->
                    {{ form.as_p }}

                    <input class="btn btn-dark" type="submit" value="Submit">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

todo/templates/todo/list.html
{% extends 'todo/base.html' %}
{% block content %}

    <div class="p-5">
        <div class="container-fluid">
            <div class="row">
               {% for item in todo_items %}
                    <div class="col-xl-6 col-md-12 mb-4">
                        <div class="card">
                            <div class="card-header">
                                <div class="float-end">
                                    <a class="link-dark link-offset-2 link-underline link-underline-opacity-0" data-bs-toggle="modal" data-bs-target="#deleteModel" data-bs-whatever="{{item.id}} {{item.title}}">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                          <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"/>
                                          <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"/>
                                        </svg>
                                    </a>
                                    <a class="link-dark link-offset-2 link-underline link-underline-opacity-0" href="{% url 'todo:create_task' %}">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                                          <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325"/>
                                        </svg>
                                    </a>
                                    <a class="link-dark link-offset-2 link-underline link-underline-opacity-0" href="{% url 'todo:create_task' %}">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check-all" viewBox="0 0 16 16">
                                          <path d="M8.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L2.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093L8.95 4.992zm-.92 5.14.92.92a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 1 0-1.091-1.028L9.477 9.417l-.485-.486z"/>
                                        </svg>
                                    </a>
                                </div>
                            </div>
                          <div class="card-body">
                            <h5 class="card-title">{{item.title}}</h5>
                            <div class="card-text">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-hourglass-top" viewBox="0 0 16 16">
                                  <path d="M2 14.5a.5.5 0 0 0 .5.5h11a.5.5 0 1 0 0-1h-1v-1a4.5 4.5 0 0 0-2.557-4.06c-.29-.139-.443-.377-.443-.59v-.7c0-.213.154-.451.443-.59A4.5 4.5 0 0 0 12.5 3V2h1a.5.5 0 0 0 0-1h-11a.5.5 0 0 0 0 1h1v1a4.5 4.5 0 0 0 2.557 4.06c.29.139.443.377.443.59v.7c0 .213-.154.451-.443.59A4.5 4.5 0 0 0 3.5 13v1h-1a.5.5 0 0 0-.5.5m2.5-.5v-1a3.5 3.5 0 0 1 1.989-3.158c.533-.256 1.011-.79 1.011-1.491v-.702s.18.101.5.101.5-.1.5-.1v.7c0 .701.478 1.236 1.011 1.492A3.5 3.5 0 0 1 11.5 13v1z"/>
                                </svg>
                                {{ item.startDate }} --
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-hourglass-bottom" viewBox="0 0 16 16">
                                  <path d="M2 1.5a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-1v1a4.5 4.5 0 0 1-2.557 4.06c-.29.139-.443.377-.443.59v.7c0 .213.154.451.443.59A4.5 4.5 0 0 1 12.5 13v1h1a.5.5 0 0 1 0 1h-11a.5.5 0 1 1 0-1h1v-1a4.5 4.5 0 0 1 2.557-4.06c.29-.139.443-.377.443-.59v-.7c0-.213-.154-.451-.443-.59A4.5 4.5 0 0 1 3.5 3V2h-1a.5.5 0 0 1-.5-.5m2.5.5v1a3.5 3.5 0 0 0 1.989 3.158c.533.256 1.011.791 1.011 1.491v.702s.18.149.5.149.5-.15.5-.15v-.7c0-.701.478-1.236 1.011-1.492A3.5 3.5 0 0 0 11.5 3V2z"/>
                                </svg>
                                {{ item.limitDate }}
                                <a class= "btn btn-link text-right" data-bs-toggle="collapse" href="#item{{ forloop.counter }}" role="button" aria-expanded="false" aria-controls="item{{ forloop.counter }}">
                                    Show details
                                </a>
                                <div class="collapse" id="item{{ forloop.counter }}">
                                    {{item.description}}
                                </div>
                            </div>
                          </div>
                        </div>
                    </div>
               {% endfor %}
            </div>
        </div>
    </div>


    <!-- Delete item Modal -->
    <div class="modal fade" id="deleteModel" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="deleteModelLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="deleteModelLabel">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="#d9534f" class="bi bi-x-circle-fill" viewBox="0 0 16 16">
                  <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0M5.354 4.646a.5.5 0 1 0-.708.708L7.293 8l-2.647 2.646a.5.5 0 0 0 .708.708L8 8.707l2.646 2.647a.5.5 0 0 0 .708-.708L8.707 8l2.647-2.646a.5.5 0 0 0-.708-.708L8 7.293z"/>
                </svg>
                Are you sure you want to delete?
            </h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
              This item will be deleted permanently. You can't undo this action
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
            <button type="button" class="btn btn-danger">Delete</button>
          </div>
        </div>
      </div>
    </div>

{% endblock %}